# The generator options are defined once in this file.
# Each option can be overridden when using the command line tool.
# Each option option can be overridden using your own config file too.
category:
    default: 'cat'
    values: [ 'none', 'cat' ]
gather_methods:
    default: 'start'
    values: ['start', 'end' ]
generic_constants_names:
    default: false
    values: [ true, false ]
generate_tutorial_file:
    default: true
    values: [ true, false ]
add_comments:
    default: [ ]
    values: null
namespace_prefix:
    default: ''
    values: ''
standalone:
    default: true
    values: [ true, false ]
struct_class:
    default: '\WsdlToPhp\PackageBase\AbstractStructBase'
    values: ''
struct_array_class:
    default: '\WsdlToPhp\PackageBase\AbstractStructArrayBase'
    values: ''
soap_client_class:
    default: '\WsdlToPhp\PackageBase\AbstractSoapClientBase'
    values: ''
origin:
    default: ''
    values: ''
destination:
    default: ''
    values: ''
prefix:
    default: ''
    values: ''
basic_login:
    default: ''
    values: ''
basic_password:
    default: ''
    values: ''
proxy_host:
    default: ''
    values: ''
proxy_port:
    default: ''
    values: ''
proxy_login:
    default: ''
    values: ''
proxy_password:
    default: ''
    values: ''
soap_options:
    default: []
    values: null